import { hsl2rgb, setpx, pixelFill, clamp } from '../core/color.js';
import { fbm } from '../core/rng.js';

// Each pattern receives (ctx, W, H, rng) and draws directly to ctx.
// Randomness is derived from rng() so output is seed-reproducible.

export function p_rothko(ctx,W,H,rng){const bh=rng()*360,n=2+rng()*3|0,mg=W*.08;ctx.fillStyle=`hsl(${(bh+180)%360},${40+rng()*30}%,${15+rng()*15}%)`;ctx.fillRect(0,0,W,H);let y=H*.05;for(let i=0;i<n;i++){const bH=H*(.2+rng()*.3),t=i/n,h=(bh+t*120)%360,g=ctx.createLinearGradient(0,y-8,0,y+bH+8);g.addColorStop(0,'transparent');g.addColorStop(.1,`hsl(${h},${60+rng()*20}%,${30+rng()*20}%)`);g.addColorStop(.9,`hsl(${h},${60+rng()*20}%,${30+rng()*20}%)`);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(mg,y,W-mg*2,bH);y+=bH+H*.04;}}
export function p_pollock(ctx,W,H,rng){const bh=rng()*360;ctx.fillStyle=`hsl(${(bh+180)%360},30%,90%)`;ctx.fillRect(0,0,W,H);for(let i=0;i<8+rng()*8|0;i++){let x=rng()*W,y=rng()*H,vx=rng()*8-4,vy=rng()*8-4;ctx.strokeStyle=`hsla(${(bh+i*30)%360},${80+rng()*20}%,${20+rng()*30}%,0.85)`;ctx.lineWidth=1+rng()*4;ctx.beginPath();ctx.moveTo(x,y);for(let s=0;s<200;s++){vx=clamp(vx+(rng()-.5)*2,-10,10);vy=clamp(vy+(rng()-.5)*2,-10,10);x=clamp(x+vx,0,W);y=clamp(y+vy,0,H);ctx.lineTo(x,y);if(rng()<.005){ctx.stroke();ctx.beginPath();ctx.moveTo(x,y);ctx.lineWidth=rng()*3;}}ctx.stroke();}}
export function p_pointillism(ctx,W,H,rng){const bh=rng()*360,sd=rng()*9999|0;ctx.fillStyle='#EEE';ctx.fillRect(0,0,W,H);for(let i=0;i<10000;i++){const x=rng()*W,y=rng()*H,v=fbm(x/W,y/H,sd,3,2);ctx.fillStyle=`hsla(${(bh+v*180)%360},${60+v*30}%,${30+v*40}%,0.8)`;ctx.beginPath();ctx.arc(x,y,1+rng()*3,0,Math.PI*2);ctx.fill();}}
export function p_watercolor(ctx,W,H,rng){const bh=rng()*360;ctx.fillStyle='#f5f5ee';ctx.fillRect(0,0,W,H);for(let layer=0;layer<8;layer++){const h=(bh+layer*25)%360,cx=W*(.2+rng()*.6),cy=H*(.2+rng()*.6),r=50+rng()*150;for(let b=0;b<4;b++){const bx=cx+(rng()-.5)*r*.8,by=cy+(rng()-.5)*r*.3,br=r*(.5+rng()*.8),g=ctx.createRadialGradient(bx,by,0,bx,by,br);g.addColorStop(0,`hsla(${h},${60+rng()*30}%,${55+rng()*25}%,0.14)`);g.addColorStop(.6,`hsla(${h},${60+rng()*30}%,${55+rng()*25}%,0.07)`);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(bx,by,br,0,Math.PI*2);ctx.fill();}}}
export function p_neon_glow(ctx,W,H,rng){const bh=rng()*360;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);for(let i=0;i<5+rng()*5|0;i++){const h=(bh+i*50)%360,type=rng()*3|0;ctx.shadowColor=`hsl(${h},100%,65%)`;ctx.shadowBlur=15;ctx.strokeStyle=`hsl(${h},100%,70%)`;ctx.lineWidth=2;if(type===0){ctx.beginPath();ctx.moveTo(rng()*W,rng()*H);ctx.quadraticCurveTo(rng()*W,rng()*H,rng()*W,rng()*H);ctx.stroke();}else if(type===1){ctx.beginPath();ctx.arc(rng()*W,rng()*H,20+rng()*80,0,Math.PI*(1+rng()));ctx.stroke();}else{ctx.strokeRect(rng()*W*.7,rng()*H*.7,50+rng()*100,50+rng()*100);}ctx.shadowBlur=0;}}
export function p_kaleidoscope(ctx,W,H,rng){const bh=rng()*360,n=4+rng()*4|0,sd=rng()*9999|0,cx=W/2,cy=H/2,slices=n*2,ang=Math.PI*2/slices;pixelFill(ctx,W,H,(x,y)=>{const dx=x-cx,dy=y-cy,r=Math.sqrt(dx*dx+dy*dy);let a=Math.atan2(dy,dx);const sectorIdx=Math.floor(((a%(Math.PI*2)+Math.PI*2)%(Math.PI*2))/ang);let fa=((a%ang)+ang)%ang;if(sectorIdx%2===1)fa=ang-fa;const nx=cx+Math.cos(fa)*r,ny=cy+Math.sin(fa)*r,v=fbm(nx/W,ny/H,sd,4,3),v2=fbm(nx/W+5,ny/H,sd+1,3,2);return hsl2rgb((bh+v*200+v2*100)%360,80,20+v*50);});}
export function p_stained_glass(ctx,W,H,rng){const bh=rng()*360,n=20+rng()*20|0,pts=Array.from({length:n},()=>({x:rng()*W,y:rng()*H,h:(bh+rng()*180)%360,s:60+rng()*30,l:35+rng()*30}));pixelFill(ctx,W,H,(x,y)=>{let d1=Infinity,d2=Infinity,bi=0;for(let i=0;i<pts.length;i++){const d=(x-pts[i].x)**2+(y-pts[i].y)**2;if(d<d1){d2=d1;d1=d;bi=i;}else if(d<d2)d2=d;}if(Math.sqrt(d2)-Math.sqrt(d1)<3)return[5,5,10];const p=pts[bi];return hsl2rgb(p.h,p.s,p.l);});}
export function p_gen_art(ctx,W,H,rng){const bh=rng()*360;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);for(let i=0;i<10+rng()*15|0;i++){const type=rng()*4|0,h=(bh+i*(360/25))%360;ctx.fillStyle=`hsla(${h},80%,55%,0.3)`;ctx.strokeStyle=`hsla(${h},90%,65%,0.6)`;ctx.lineWidth=1+rng()*2;if(type===0){ctx.beginPath();ctx.arc(rng()*W,rng()*H,20+rng()*120,0,Math.PI*2);rng()<.5?ctx.fill():ctx.stroke();}else if(type===1){ctx.save();ctx.translate(rng()*W,rng()*H);ctx.rotate(rng()*Math.PI);const s=30+rng()*120;rng()<.5?ctx.fillRect(-s/2,-s/2,s,s):ctx.strokeRect(-s/2,-s/2,s,s);ctx.restore();}else if(type===2){const pp=3+rng()*5|0,cx=rng()*W,cy=rng()*H,r=30+rng()*100;ctx.beginPath();for(let k=0;k<pp;k++){const a2=k/pp*Math.PI*2;k?ctx.lineTo(cx+r*Math.cos(a2),cy+r*Math.sin(a2)):ctx.moveTo(cx+r*Math.cos(a2),cy+r*Math.sin(a2));}ctx.closePath();rng()<.5?ctx.fill():ctx.stroke();}else{ctx.beginPath();ctx.moveTo(rng()*W,rng()*H);for(let k=0;k<3;k++)ctx.bezierCurveTo(rng()*W,rng()*H,rng()*W,rng()*H,rng()*W,rng()*H);ctx.stroke();}}}
export function p_color_wash(ctx,W,H,rng){const bh=rng()*360,n=6+rng()*6|0;ctx.fillStyle=`hsl(${bh},50%,15%)`;ctx.fillRect(0,0,W,H);for(let i=0;i<n;i++){const h=(bh+i*(360/n))%360,x=rng()*W,y=rng()*H,r=100+rng()*200,g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,`hsla(${h},90%,60%,0.6)`);g.addColorStop(.5,`hsla(${h},80%,40%,0.3)`);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}}
export function p_glitch_noise(ctx,W,H,rng){const id=ctx.createImageData(W,H),d=id.data;for(let y=0;y<H;y++){const rowH=rng()*360;for(let x=0;x<W;x++){const v=rng(),i=(y*W+x)*4;if(v>.7){const[r,g,b]=hsl2rgb((rowH+rng()*60)%360,80,30+v*60);setpx(d,i,r,g,b);}else{const bw=rng()*30|0;setpx(d,i,bw,bw,bw);}}}ctx.putImageData(id,0,0);}
