
// Each pattern receives (ctx, W, H, rng) and draws directly to ctx.
// Randomness is derived from rng() so output is seed-reproducible.


export function p_rect_grid(ctx,W,H,rng){const cols=4+rng()*8|0,rows=4+rng()*8|0,bh=rng()*360;for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){ctx.fillStyle=`hsl(${(bh+c*25+r*20+rng()*20)%360},${50+rng()*40}%,${25+rng()*40}%)`;ctx.fillRect(c*(W/cols),r*(H/rows),W/cols+1,H/rows+1);}}
export function p_hex_grid(ctx,W,H,rng){const sz=20+rng()*30|0,bh=rng()*360,hw=sz*Math.sqrt(3),hh=sz*1.5;ctx.fillStyle=`hsl(${bh},60%,10%)`;ctx.fillRect(0,0,W,H);for(let row=0;row<H/hh+2;row++)for(let col=0;col<W/hw+2;col++){const x=col*hw+(row%2?hw/2:0),y=row*hh;ctx.beginPath();for(let i=0;i<6;i++){const a=Math.PI/6+i*Math.PI/3;i?ctx.lineTo(x+sz*Math.cos(a),y+sz*Math.sin(a)):ctx.moveTo(x+sz*Math.cos(a),y+sz*Math.sin(a));}ctx.closePath();ctx.fillStyle=`hsl(${(bh+col*20+row*15)%360},${60+rng()*30}%,${25+rng()*35}%)`;ctx.fill();}}
export function p_iso_grid(ctx,W,H,rng){const bh=rng()*360,sz=30+rng()*20|0,cols=W/(sz*2)+3|0,rows=H/sz+3|0;ctx.fillStyle='#050510';ctx.fillRect(0,0,W,H);for(let r=0;r<rows;r++)for(let c=0;c<cols;c++){const x=c*sz*2+(r%2)*sz,y=r*sz*.866,h=(bh+c*20+r*25)%360,h3=sz*.577;ctx.fillStyle=`hsl(${h},70%,55%)`;ctx.beginPath();ctx.moveTo(x,y-h3);ctx.lineTo(x+sz,y);ctx.lineTo(x,y+h3);ctx.lineTo(x-sz,y);ctx.closePath();ctx.fill();ctx.fillStyle=`hsl(${h},70%,35%)`;ctx.beginPath();ctx.moveTo(x-sz,y);ctx.lineTo(x,y+h3);ctx.lineTo(x,y+h3+sz);ctx.lineTo(x-sz,y+sz);ctx.closePath();ctx.fill();ctx.fillStyle=`hsl(${h},70%,25%)`;ctx.beginPath();ctx.moveTo(x+sz,y);ctx.lineTo(x,y+h3);ctx.lineTo(x,y+h3+sz);ctx.lineTo(x+sz,y+sz);ctx.closePath();ctx.fill();}}
export function p_tri_grid(ctx,W,H,rng){const sz=25+rng()*25|0,bh=rng()*360,h2=sz*Math.sin(Math.PI/3);ctx.fillStyle=`hsl(${bh},50%,10%)`;ctx.fillRect(0,0,W,H);for(let row=0;row<H/h2+2;row++)for(let col=0;col<W/sz*2+2;col++){const x=(col-row%2)*sz/2,y=row*h2,up=(col+row)%2===0;ctx.beginPath();if(up){ctx.moveTo(x,y+h2);ctx.lineTo(x+sz,y+h2);ctx.lineTo(x+sz/2,y);}else{ctx.moveTo(x+sz/2,y+h2);ctx.lineTo(x,y);ctx.lineTo(x+sz,y);}ctx.closePath();ctx.fillStyle=`hsl(${(bh+col*17+row*23)%360},${60+rng()*30}%,${25+rng()*35}%)`;ctx.fill();}}
export function p_diamond_grid(ctx,W,H,rng){const bh=rng()*360,sz=25+rng()*25|0;for(let r=0;r<H/(sz*2)+2;r++)for(let c=0;c<W/(sz*2)+2;c++){ctx.save();ctx.translate(c*sz*2+(r%2)*sz*2,r*sz*2-(r%2)*sz);ctx.rotate(Math.PI/4);ctx.fillStyle=`hsl(${(bh+c*20+r*25)%360},${60+rng()*30}%,${25+rng()*35}%)`;ctx.fillRect(-sz/2,-sz/2,sz,sz);ctx.restore();}}
export function p_concentric_c(ctx,W,H,rng){const cx=W*(.3+rng()*.4),cy=H*(.3+rng()*.4),bh=rng()*360,n=20+rng()*20|0;ctx.fillStyle=`hsl(${bh},60%,10%)`;ctx.fillRect(0,0,W,H);for(let i=n;i>=0;i--){const t=i/n;ctx.beginPath();ctx.arc(cx,cy,t*Math.max(W,H)*.7,0,Math.PI*2);ctx.fillStyle=`hsl(${(bh+t*280)%360},${70+t*20}%,${15+t*40}%)`;ctx.fill();}}
export function p_concentric_s(ctx,W,H,rng){const bh=rng()*360,n=20+rng()*15|0,rot=rng()*Math.PI/4;ctx.fillStyle=`hsl(${bh},60%,10%)`;ctx.fillRect(0,0,W,H);for(let i=n;i>=0;i--){const t=i/n,s2=t*Math.max(W,H)*.75;ctx.save();ctx.translate(W/2,H/2);ctx.rotate(rot+t*.5);ctx.fillStyle=`hsl(${(bh+t*280)%360},70%,${15+t*40}%)`;ctx.fillRect(-s2/2,-s2/2,s2,s2);ctx.restore();}}
export function p_concentric_h(ctx,W,H,rng){const bh=rng()*360,n=15+rng()*10|0;ctx.fillStyle=`hsl(${bh},60%,10%)`;ctx.fillRect(0,0,W,H);for(let i=n;i>=0;i--){const t=i/n,r2=t*Math.min(W,H)*.55;ctx.beginPath();for(let k=0;k<6;k++){const a=k*Math.PI/3;k?ctx.lineTo(W/2+r2*Math.cos(a),H/2+r2*Math.sin(a)):ctx.moveTo(W/2+r2*Math.cos(a),H/2+r2*Math.sin(a));}ctx.closePath();ctx.fillStyle=`hsl(${(bh+t*280)%360},70%,${15+t*40}%)`;ctx.fill();}}
export function p_chevrons(ctx,W,H,rng){const bh=rng()*360,n=10+rng()*20|0,h2=H/n;for(let i=0;i<n;i++){const t=i/n;ctx.beginPath();ctx.moveTo(0,i*h2+h2);ctx.lineTo(W/2,i*h2);ctx.lineTo(W,i*h2+h2);ctx.lineTo(W,i*h2+h2*2);ctx.lineTo(W/2,i*h2+h2);ctx.lineTo(0,i*h2+h2*2);ctx.closePath();ctx.fillStyle=`hsl(${(bh+t*360)%360},${70+rng()*20}%,${25+t*30}%)`;ctx.fill();}}
export function p_mondrian(ctx,W,H,rng){const rects=[];function split(x,y,w,h,depth){if(depth===0||w<40||h<40){rects.push({x,y,w,h});return;}if(rng()<.5){const s=w*(.2+rng()*.6)|0;split(x,y,s,h,depth-1);split(x+s,y,w-s,h,depth-1);}else{const s=h*(.2+rng()*.6)|0;split(x,y,w,s,depth-1);split(x,y+s,w,h-s,depth-1);}}split(0,0,W,H,5);const clrs=['#E63946','#457B9D','#F4A261','#2A9D8F','#fff','#fff','#fff','#0A0A0A'];for(const r of rects){ctx.fillStyle=clrs[rng()*clrs.length|0];ctx.fillRect(r.x+2,r.y+2,r.w-4,r.h-4);ctx.strokeStyle='#0A0A0A';ctx.lineWidth=4;ctx.strokeRect(r.x,r.y,r.w,r.h);}}
export function p_bauhaus(ctx,W,H,rng){const bh=rng()*360;ctx.fillStyle=`hsl(${bh},15%,92%)`;ctx.fillRect(0,0,W,H);for(let i=0;i<8+rng()*7|0;i++){const type=rng()*3|0,h=(bh+i*50)%360,x=rng()*W,y=rng()*H,s=50+rng()*150;ctx.fillStyle=`hsl(${h},85%,45%)`;if(type===0){ctx.fillRect(x-s/2,y-s/2,s,s);}else if(type===1){ctx.beginPath();ctx.arc(x,y,s/2,0,Math.PI*2);ctx.fill();}else{ctx.save();ctx.translate(x,y);ctx.rotate(rng()*Math.PI);ctx.fillRect(-s/2,-s/6,s,s/3);ctx.restore();}}}
export function p_hard_edge(ctx,W,H,rng){const bh=rng()*360,n=3+rng()*5|0;ctx.fillStyle=`hsl(${bh},70%,40%)`;ctx.fillRect(0,0,W,H);for(let i=0;i<n;i++){ctx.fillStyle=`hsl(${(bh+i*60)%360},80%,${30+rng()*30}%)`;ctx.fillRect(rng()*W-50,rng()*H-50,100+rng()*(W-100),100+rng()*(H-100));}}
export function p_radial_burst(ctx,W,H,rng){const cx=W/2,cy=H/2,bh=rng()*360,n=20+rng()*40|0;ctx.fillStyle=`hsl(${bh},60%,8%)`;ctx.fillRect(0,0,W,H);for(let i=0;i<n;i++){const a1=i/n*Math.PI*2,a2=(i+.4)/n*Math.PI*2,r=Math.max(W,H),g=ctx.createRadialGradient(cx,cy,0,cx,cy,r),h=(bh+i/n*360)%360;g.addColorStop(0,`hsla(${h},90%,80%,0.9)`);g.addColorStop(1,`hsla(${h},80%,30%,0)`);ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a1,a2);ctx.closePath();ctx.fill();}}
export function p_nested_tri(ctx,W,H,rng){const bh=rng()*360,n=12+rng()*8|0;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);for(let i=n;i>=0;i--){const t=i/n,s=t*Math.min(W,H)*.48;ctx.save();ctx.translate(W/2,H/2);ctx.rotate(t*Math.PI*.5);ctx.beginPath();ctx.moveTo(0,-s);ctx.lineTo(s*.866,s*.5);ctx.lineTo(-s*.866,s*.5);ctx.closePath();ctx.fillStyle=`hsl(${(bh+t*360)%360},80%,${15+t*45}%)`;ctx.fill();ctx.restore();}}
export function p_mosaic(ctx,W,H,rng){const sz=8+rng()*16|0,bh=rng()*360;for(let r=0;r<H/sz+1;r++)for(let c=0;c<W/sz+1;c++){ctx.fillStyle=`hsl(${(bh+c*8+r*7+rng()*20)%360},${55+rng()*35}%,${25+rng()*40}%)`;ctx.fillRect(c*sz,r*sz,sz,sz);}}
export function p_brick_wall(ctx,W,H,rng){const bh=rng()*360,bw=60+rng()*40|0,bh2=25+rng()*15|0;for(let r=0;r<H/bh2+1;r++){const off=(r%2)*bw/2;for(let c=-1;c<W/bw+2;c++){ctx.fillStyle=`hsl(${(bh+rng()*20)%360},${45+rng()*25}%,${30+rng()*20}%)`;ctx.fillRect(c*bw-off+1,r*bh2+1,bw-2,bh2-2);}}}
export function p_herringbone(ctx,W,H,rng){const bh=rng()*360,sz=20+rng()*20|0;for(let r=-2;r<H/sz+4;r++)for(let c=-2;c<W/sz+4;c++){const x=c*sz*2,y=r*sz,h=(bh+c*15+r*10)%360;ctx.fillStyle=`hsl(${h},60%,${30+rng()*20}%)`;ctx.save();ctx.translate(x,y);ctx.rotate(Math.PI/4);ctx.fillRect(-sz/2,-sz*.25,sz,sz*.5);ctx.restore();ctx.fillStyle=`hsl(${(h+30)%360},60%,${30+rng()*20}%)`;ctx.save();ctx.translate(x+sz,y);ctx.rotate(-Math.PI/4);ctx.fillRect(-sz/2,-sz*.25,sz,sz*.5);ctx.restore();}}
export function p_plaid(ctx,W,H,rng){const bh=rng()*360,n=5+rng()*6|0;ctx.fillStyle=`hsl(${bh},60%,25%)`;ctx.fillRect(0,0,W,H);for(let i=0;i<n;i++){const pos=rng(),width=.03+rng()*.06,h=(bh+rng()*180)%360,a=.5+rng()*.5;ctx.fillStyle=`hsla(${h},80%,60%,${a})`;ctx.fillRect(0,pos*H,W,width*H);ctx.fillRect(pos*W,0,width*W,H);}}
export function p_spiral_sq(ctx,W,H,rng){const bh=rng()*360,n=20+rng()*15|0;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);for(let i=n;i>=0;i--){const t=i/n,s=t*Math.min(W,H)*.5;ctx.save();ctx.translate(W/2,H/2);ctx.rotate(t*Math.PI*2);ctx.fillStyle=`hsl(${(bh+t*360)%360},80%,${15+t*45}%)`;ctx.fillRect(-s/2,-s/2,s,s);ctx.restore();}}
export function p_pinwheel(ctx,W,H,rng){const cx=W/2,cy=H/2,n=4+rng()*8|0,bh=rng()*360,r=Math.min(W,H)*.5;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);for(let i=0;i<n*2;i++){const a1=i/n*Math.PI,a2=(i+1)/n*Math.PI,g=ctx.createRadialGradient(cx,cy,0,cx,cy,r),h=(bh+i/n*180)%360;g.addColorStop(0,`hsl(${h},90%,70%)`);g.addColorStop(1,`hsl(${(h+40)%360},80%,30%)`);ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a1,a2);ctx.closePath();ctx.fill();}}

