import { p_linear_grad,p_radial_grad,p_conic_grad,p_mesh_grad,p_mandelbrot,p_julia,p_burning_ship,p_lissajous,p_rose_curve,p_spirograph,p_fib_spiral,p_hilbert,p_moire,p_truchet,p_voronoi,p_lorenz,p_clifford,p_dejong,p_sine_field,p_interference } from './mathematical.js';
import { p_rect_grid,p_hex_grid,p_iso_grid,p_tri_grid,p_diamond_grid,p_concentric_c,p_concentric_s,p_concentric_h,p_chevrons,p_mondrian,p_bauhaus,p_hard_edge,p_radial_burst,p_nested_tri,p_mosaic,p_brick_wall,p_herringbone,p_plaid,p_spiral_sq,p_pinwheel } from './geometric.js';
import { p_marble,p_wood_grain,p_camouflage,p_bubbles,p_cells,p_coral,p_crystal,p_lightning,p_cracks,p_sand_dunes,p_water_ripple,p_aurora,p_clouds,p_lava_lamp,p_frost,p_feathers,p_scales,p_leaf_veins,p_terrain,p_oil_slick } from './natural.js';
import { p_oscilloscope,p_spectrum,p_waveform,p_tv_static,p_circuit,p_radar,p_halftone,p_crosshatch,p_scan_lines,p_binary_rain,p_barcode,p_heat_map,p_contour,p_dot_matrix,p_sort_base } from './signal.js';
import { p_flow_field,p_react_diff,p_dla,p_gravity,p_magnetic,p_lsystem,p_cellular,p_particle_burst,p_plasma,p_point_cloud,p_ifs_fern,p_brownian,p_noise_field,p_perlin_terrain,p_galaxy } from './generative.js';
import { p_rothko,p_pollock,p_pointillism,p_watercolor,p_neon_glow,p_kaleidoscope,p_stained_glass,p_gen_art,p_color_wash,p_glitch_noise } from './artistic.js';
import { TEXTURE_MINERAL_PATTERNS } from './texture-mineral.js';
import { TEXTURE_ORGANIC_PATTERNS } from './texture-organic.js';

// Central registry of all 100 generative patterns, each tagged with its family.
// Patterns are hidden from the user in the Visual tab (auto-picked from seed),
// but the family tag also lets the overlay effects (effects/image/overlay.js)
// pull from a curated pool instead of the full 100.
export const PATTERNS = [
  {id:'linear_grad',label:'Linear Gradient',fn:p_linear_grad,family:"mathematical"},
  {id:'radial_grad',label:'Radial Gradient',fn:p_radial_grad,family:"mathematical"},
  {id:'conic_grad',label:'Conic Gradient',fn:p_conic_grad,family:"mathematical"},
  {id:'mesh_grad',label:'Mesh Gradient',fn:p_mesh_grad,family:"mathematical"},
  {id:'mandelbrot',label:'Mandelbrot',fn:p_mandelbrot,family:"mathematical"},
  {id:'julia',label:'Julia Set',fn:p_julia,family:"mathematical"},
  {id:'burning_ship',label:'Burning Ship',fn:p_burning_ship,family:"mathematical"},
  {id:'lissajous',label:'Lissajous',fn:p_lissajous,family:"mathematical"},
  {id:'rose_curve',label:'Rose Curve',fn:p_rose_curve,family:"mathematical"},
  {id:'spirograph',label:'Spirograph',fn:p_spirograph,family:"mathematical"},
  {id:'fib_spiral',label:'Fibonacci Spiral',fn:p_fib_spiral,family:"mathematical"},
  {id:'hilbert',label:'Hilbert Curve',fn:p_hilbert,family:"mathematical"},
  {id:'moire',label:'Moiré',fn:p_moire,family:"mathematical"},
  {id:'truchet',label:'Truchet Tiles',fn:p_truchet,family:"mathematical"},
  {id:'voronoi',label:'Voronoi',fn:p_voronoi,family:"mathematical"},
  {id:'lorenz',label:'Lorenz Attractor',fn:p_lorenz,family:"mathematical"},
  {id:'clifford',label:'Clifford Attractor',fn:p_clifford,family:"mathematical"},
  {id:'dejong',label:'De Jong Attractor',fn:p_dejong,family:"mathematical"},
  {id:'sine_field',label:'Sine Field',fn:p_sine_field,family:"mathematical"},
  {id:'interference',label:'Interference',fn:p_interference,family:"mathematical"},
  {id:'rect_grid',label:'Rect Grid',fn:p_rect_grid,family:"geometric"},
  {id:'hex_grid',label:'Hex Grid',fn:p_hex_grid,family:"geometric"},
  {id:'iso_grid',label:'Isometric Grid',fn:p_iso_grid,family:"geometric"},
  {id:'tri_grid',label:'Triangle Grid',fn:p_tri_grid,family:"geometric"},
  {id:'diamond_grid',label:'Diamond Grid',fn:p_diamond_grid,family:"geometric"},
  {id:'concentric_c',label:'Concentric Circles',fn:p_concentric_c,family:"geometric"},
  {id:'concentric_s',label:'Concentric Squares',fn:p_concentric_s,family:"geometric"},
  {id:'concentric_h',label:'Concentric Hex',fn:p_concentric_h,family:"geometric"},
  {id:'chevrons',label:'Chevrons',fn:p_chevrons,family:"geometric"},
  {id:'mondrian',label:'Mondrian',fn:p_mondrian,family:"geometric"},
  {id:'bauhaus',label:'Bauhaus',fn:p_bauhaus,family:"geometric"},
  {id:'hard_edge',label:'Hard Edge',fn:p_hard_edge,family:"geometric"},
  {id:'radial_burst',label:'Radial Burst',fn:p_radial_burst,family:"geometric"},
  {id:'nested_tri',label:'Nested Triangles',fn:p_nested_tri,family:"geometric"},
  {id:'mosaic',label:'Mosaic',fn:p_mosaic,family:"geometric"},
  {id:'brick_wall',label:'Brick Wall',fn:p_brick_wall,family:"geometric"},
  {id:'herringbone',label:'Herringbone',fn:p_herringbone,family:"geometric"},
  {id:'plaid',label:'Plaid',fn:p_plaid,family:"geometric"},
  {id:'spiral_sq',label:'Spiral Squares',fn:p_spiral_sq,family:"geometric"},
  {id:'pinwheel',label:'Pinwheel',fn:p_pinwheel,family:"geometric"},
  {id:'marble',label:'Marble',fn:p_marble,family:"natural"},
  {id:'wood_grain',label:'Wood Grain',fn:p_wood_grain,family:"natural"},
  {id:'camouflage',label:'Camouflage',fn:p_camouflage,family:"natural"},
  {id:'bubbles',label:'Bubbles',fn:p_bubbles,family:"natural"},
  {id:'cells',label:'Bio Cells',fn:p_cells,family:"natural"},
  {id:'coral',label:'Coral',fn:p_coral,family:"natural"},
  {id:'crystal',label:'Crystals',fn:p_crystal,family:"natural"},
  {id:'lightning',label:'Lightning',fn:p_lightning,family:"natural"},
  {id:'cracks',label:'Cracks',fn:p_cracks,family:"natural"},
  {id:'sand_dunes',label:'Sand Dunes',fn:p_sand_dunes,family:"natural"},
  {id:'water_ripple',label:'Water Ripple',fn:p_water_ripple,family:"natural"},
  {id:'aurora',label:'Aurora',fn:p_aurora,family:"natural"},
  {id:'clouds',label:'Clouds',fn:p_clouds,family:"natural"},
  {id:'lava_lamp',label:'Lava Lamp',fn:p_lava_lamp,family:"natural"},
  {id:'frost',label:'Frost',fn:p_frost,family:"natural"},
  {id:'feathers',label:'Feathers',fn:p_feathers,family:"natural"},
  {id:'scales',label:'Scales',fn:p_scales,family:"natural"},
  {id:'leaf_veins',label:'Leaf Veins',fn:p_leaf_veins,family:"natural"},
  {id:'terrain',label:'Terrain',fn:p_terrain,family:"natural"},
  {id:'oil_slick',label:'Oil Slick',fn:p_oil_slick,family:"natural"},
  {id:'oscilloscope',label:'Oscilloscope',fn:p_oscilloscope,family:"signal"},
  {id:'spectrum',label:'Spectrum',fn:p_spectrum,family:"signal"},
  {id:'waveform',label:'Waveform',fn:p_waveform,family:"signal"},
  {id:'tv_static',label:'TV Static',fn:p_tv_static,family:"signal"},
  {id:'circuit',label:'Circuit',fn:p_circuit,family:"signal"},
  {id:'radar',label:'Radar',fn:p_radar,family:"signal"},
  {id:'halftone',label:'Halftone',fn:p_halftone,family:"signal"},
  {id:'crosshatch',label:'Crosshatch',fn:p_crosshatch,family:"signal"},
  {id:'scan_lines',label:'Scan Lines',fn:p_scan_lines,family:"signal"},
  {id:'binary_rain',label:'Binary Rain',fn:p_binary_rain,family:"signal"},
  {id:'barcode',label:'Barcode',fn:p_barcode,family:"signal"},
  {id:'heat_map',label:'Heat Map',fn:p_heat_map,family:"signal"},
  {id:'contour',label:'Contour Map',fn:p_contour,family:"signal"},
  {id:'dot_matrix',label:'Dot Matrix',fn:p_dot_matrix,family:"signal"},
  {id:'sort_base',label:'Sort Base',fn:p_sort_base,family:"signal"},
  {id:'flow_field',label:'Flow Field',fn:p_flow_field,family:"generative"},
  {id:'react_diff',label:'Reaction Diffusion',fn:p_react_diff,family:"generative"},
  {id:'dla',label:'DLA Growth',fn:p_dla,family:"generative"},
  {id:'gravity',label:'Gravity Lines',fn:p_gravity,family:"generative"},
  {id:'magnetic',label:'Magnetic Field',fn:p_magnetic,family:"generative"},
  {id:'lsystem',label:'L-System Tree',fn:p_lsystem,family:"generative"},
  {id:'cellular',label:'Cellular Auto',fn:p_cellular,family:"generative"},
  {id:'particle_burst',label:'Particle Burst',fn:p_particle_burst,family:"generative"},
  {id:'plasma',label:'Plasma',fn:p_plasma,family:"generative"},
  {id:'point_cloud',label:'Point Cloud',fn:p_point_cloud,family:"generative"},
  {id:'ifs_fern',label:'IFS Fern',fn:p_ifs_fern,family:"generative"},
  {id:'brownian',label:'Brownian Motion',fn:p_brownian,family:"generative"},
  {id:'noise_field',label:'Noise Field',fn:p_noise_field,family:"generative"},
  {id:'perlin_terrain',label:'Perlin Terrain',fn:p_perlin_terrain,family:"generative"},
  {id:'galaxy',label:'Galaxy Spiral',fn:p_galaxy,family:"generative"},
  {id:'rothko',label:'Rothko',fn:p_rothko,family:"artistic"},
  {id:'pollock',label:'Pollock Drip',fn:p_pollock,family:"artistic"},
  {id:'pointillism',label:'Pointillism',fn:p_pointillism,family:"artistic"},
  {id:'watercolor',label:'Watercolor',fn:p_watercolor,family:"artistic"},
  {id:'neon_glow',label:'Neon Glow',fn:p_neon_glow,family:"artistic"},
  {id:'kaleidoscope',label:'Kaleidoscope',fn:p_kaleidoscope,family:"artistic"},
  {id:'stained_glass',label:'Stained Glass',fn:p_stained_glass,family:"artistic"},
  {id:'gen_art',label:'Generative Art',fn:p_gen_art,family:"artistic"},
  {id:'color_wash',label:'Color Wash',fn:p_color_wash,family:"artistic"},
  {id:'glitch_noise',label:'Glitch Noise',fn:p_glitch_noise,family:"artistic"},
  ...TEXTURE_MINERAL_PATTERNS,
  ...TEXTURE_ORGANIC_PATTERNS,
];
export function getPatternById(id) {
  return PATTERNS.find((p) => p.id === id);
}
