import { hsl2rgb, setpx, pixelFill, lerp, clamp } from '../core/color.js';
import { fbm } from '../core/rng.js';

// Each pattern receives (ctx, W, H, rng) and draws directly to ctx.
// Randomness is derived from rng() so output is seed-reproducible.


export function p_oscilloscope(ctx,W,H,rng){const bh=rng()*360,n=2+rng()*4|0;ctx.fillStyle='#030808';ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(0,100,0,0.2)';ctx.lineWidth=.5;for(let i=0;i<10;i++){ctx.beginPath();ctx.moveTo(i*W/10,0);ctx.lineTo(i*W/10,H);ctx.stroke();}for(let i=0;i<8;i++){ctx.beginPath();ctx.moveTo(0,i*H/8);ctx.lineTo(W,i*H/8);ctx.stroke();}for(let w=0;w<n;w++){const freq=.5+rng()*3,amp=H*(.15+rng()*.2),ph=rng()*Math.PI*2;ctx.beginPath();ctx.strokeStyle=`hsl(${(bh+w*80)%360},90%,65%)`;ctx.lineWidth=2;for(let x=0;x<=W;x++){const y=H/2+Math.sin(x/W*freq*Math.PI*2+ph)*amp+Math.sin(x/W*freq*3*Math.PI*2)*amp*.3;x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}}
export function p_spectrum(ctx,W,H,rng){const bh=rng()*360,n=32+rng()*32|0,bw=W/n;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);for(let i=0;i<n;i++){const h=(bh+i/n*360)%360,barH=H*(.1+rng()*.8),g=ctx.createLinearGradient(0,H-barH,0,H);g.addColorStop(0,`hsl(${h},90%,70%)`);g.addColorStop(1,`hsl(${h},70%,30%)`);ctx.fillStyle=g;ctx.fillRect(i*bw+1,H-barH,bw-2,barH);ctx.fillStyle=`hsl(${h},100%,90%)`;ctx.fillRect(i*bw+1,H-barH-4,bw-2,3);}}
export function p_waveform(ctx,W,H,rng){const bh=rng()*360,sd=rng()*9999|0;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);const waves=Array.from({length:W},(_,i)=>fbm(i/W,0,sd,4,3)*2-1);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,`hsla(${bh},90%,60%,0.8)`);g.addColorStop(.5,`hsla(${bh},90%,50%,0.2)`);g.addColorStop(1,`hsla(${bh},90%,60%,0.8)`);ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(0,H/2);for(let i=0;i<W;i++)ctx.lineTo(i,H/2+waves[i]*H*.35);ctx.lineTo(W,H/2);ctx.closePath();ctx.fill();ctx.strokeStyle=`hsl(${bh},90%,70%)`;ctx.lineWidth=1.5;ctx.beginPath();for(let i=0;i<W;i++)i?ctx.lineTo(i,H/2+waves[i]*H*.35):ctx.moveTo(i,H/2+waves[i]*H*.35);ctx.stroke();}
export function p_tv_static(ctx,W,H,rng){const bh=rng()*360,id=ctx.createImageData(W,H),d=id.data;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const v=rng(),col=v>.85,i=(y*W+x)*4;if(col){const[r,g,b]=hsl2rgb((bh+rng()*60)%360,70,50+v*40);setpx(d,i,r,g,b);}else{const bw=v*80|0;setpx(d,i,bw,bw,bw);}}ctx.putImageData(id,0,0);for(let y=0;y<H;y+=2){ctx.fillStyle='rgba(0,0,0,0.18)';ctx.fillRect(0,y,W,1);}}
export function p_circuit(ctx,W,H,rng){const bh=rng()*360,grid=30+rng()*20|0;ctx.fillStyle=`hsl(${bh},40%,8%)`;ctx.fillRect(0,0,W,H);const cols=W/grid|0,rows=H/grid|0,nodes=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)if(rng()<.4)nodes.push({x:c*grid+grid/2,y:r*grid+grid/2});ctx.strokeStyle=`hsl(${(bh+120)%360},80%,45%)`;ctx.lineWidth=1.5;for(const n of nodes){for(const[dx,dy]of[[grid,0],[0,grid],[-grid,0],[0,-grid]])if(rng()<.4){ctx.beginPath();ctx.moveTo(n.x,n.y);ctx.lineTo(n.x+dx,n.y+dy);ctx.stroke();}ctx.fillStyle=`hsl(${(bh+100)%360},90%,60%)`;ctx.beginPath();ctx.arc(n.x,n.y,2,0,Math.PI*2);ctx.fill();}}
export function p_radar(ctx,W,H,rng){const cx=W/2,cy=H/2,maxR=Math.min(W,H)*.48;ctx.fillStyle='#030808';ctx.fillRect(0,0,W,H);for(let r=1;r<=5;r++){ctx.strokeStyle='rgba(0,200,80,0.3)';ctx.lineWidth=1;ctx.beginPath();ctx.arc(cx,cy,r*maxR/5,0,Math.PI*2);ctx.stroke();}ctx.strokeStyle='rgba(0,200,80,0.2)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(cx-maxR,cy);ctx.lineTo(cx+maxR,cy);ctx.stroke();ctx.beginPath();ctx.moveTo(cx,cy-maxR);ctx.lineTo(cx,cy+maxR);ctx.stroke();const sa=rng()*Math.PI*2,g=ctx.createLinearGradient(cx,cy,cx+Math.cos(sa)*maxR,cy+Math.sin(sa)*maxR);g.addColorStop(0,'rgba(0,255,100,0.5)');g.addColorStop(1,'rgba(0,255,100,0)');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,maxR,sa-.4,sa);ctx.closePath();ctx.fill();for(let i=0;i<8+rng()*12|0;i++){const a=rng()*Math.PI*2,r2=(.2+rng()*.7)*maxR,bx=cx+Math.cos(a)*r2,by=cy+Math.sin(a)*r2,glow=ctx.createRadialGradient(bx,by,0,bx,by,5);glow.addColorStop(0,'rgba(0,255,100,0.9)');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(bx,by,5,0,Math.PI*2);ctx.fill();}}
export function p_halftone(ctx,W,H,rng){const bh=rng()*360,sp=8+rng()*8|0;ctx.fillStyle=`hsl(${(bh+180)%360},60%,15%)`;ctx.fillRect(0,0,W,H);for(let r=0;r<H/sp+1;r++)for(let c=0;c<W/sp+1;c++){const x=c*sp+(r%2)*sp/2,y=r*sp,d=Math.sqrt((x-W/2)**2+(y-H/2)**2)/Math.max(W,H)*2;ctx.fillStyle=`hsl(${(bh+c*5+r*4)%360},80%,${40+d*20}%)`;ctx.beginPath();ctx.arc(x,y,sp*.45*(1-d*.4),0,Math.PI*2);ctx.fill();}}
export function p_crosshatch(ctx,W,H,rng){const bh=rng()*360,sp=4+rng()*8|0,ang=rng()*Math.PI/4,diag=Math.sqrt(W*W+H*H);ctx.fillStyle=`hsl(${(bh+180)%360},50%,15%)`;ctx.fillRect(0,0,W,H);for(let dir=0;dir<4;dir++){const a=ang+dir*Math.PI/2;ctx.strokeStyle=`hsla(${(bh+dir*30)%360},80%,60%,0.4)`;ctx.lineWidth=1;for(let d=-diag;d<diag;d+=sp){ctx.beginPath();ctx.moveTo(W/2+Math.cos(a)*diag+Math.sin(a)*d,H/2+Math.sin(a)*diag-Math.cos(a)*d);ctx.lineTo(W/2-Math.cos(a)*diag+Math.sin(a)*d,H/2-Math.sin(a)*diag-Math.cos(a)*d);ctx.stroke();}}}
export function p_scan_lines(ctx,W,H,rng){const bh=rng()*360,n=20+rng()*30|0;for(let i=0;i<n;i++){ctx.fillStyle=`hsl(${(bh+i/n*360)%360},80%,${20+i/n*50}%)`;ctx.fillRect(0,i/n*H,W,H/n);ctx.fillStyle='rgba(0,0,0,0.28)';ctx.fillRect(0,i/n*H,W,1);}}
export function p_binary_rain(ctx,W,H,rng){const bh=rng()*360;ctx.fillStyle='#030808';ctx.fillRect(0,0,W,H);ctx.font='12px monospace';const cols=W/12|0;for(let c=0;c<cols;c++){const len=5+rng()*20|0,startY=rng()*H,h=(bh+c*10)%360;for(let i=0;i<len;i++){ctx.fillStyle=i===0?`hsl(${h},10%,95%)`:`hsla(${h},90%,55%,${1-i/len})`;ctx.fillText(rng()<.5?'0':'1',c*12+2,(startY+i*14)%H+14);}}}
export function p_barcode(ctx,W,H,rng){const bh=rng()*360;ctx.fillStyle=`hsl(${(bh+180)%360},30%,90%)`;ctx.fillRect(0,0,W,H);let x=10;while(x<W-10){const w=1+rng()*5|0;if(rng()<.5){ctx.fillStyle=`hsl(${(bh+rng()*20)%360},80%,15%)`;const sy=H*.1+rng()*H*.05,bh2=rng()<.1?H*rng():H*.7;ctx.fillRect(x,sy,w,bh2);}x+=w+1;}}
export function p_heat_map(ctx,W,H,rng){const n=3+rng()*5|0,hot=Array.from({length:n},()=>({x:rng()*W,y:rng()*H,i:.5+rng()*.5}));pixelFill(ctx,W,H,(x,y)=>{let h=0;for(const s of hot)h+=s.i*Math.exp(-((x-s.x)**2+(y-s.y)**2)/(W*H*.02));h=clamp(h,0,1);if(h<.25)return hsl2rgb(240,90,15+h*40);if(h<.5)return hsl2rgb(lerp(240,60,(h-.25)/.25),90,35+h*20);if(h<.75)return hsl2rgb(lerp(60,0,(h-.5)/.25),90,50+h*10);return hsl2rgb(0,90,60+h*15);});}
export function p_contour(ctx,W,H,rng){const sd=rng()*9999|0,bh=rng()*360,lvls=10+rng()*10|0;pixelFill(ctx,W,H,(_,__,nx,ny)=>{const h=fbm(nx,ny,sd,5,2),lvl=Math.floor(h*lvls)/lvls;if(Math.abs(h-lvl)<.014)return[8,8,12];return hsl2rgb((bh+lvl*360)%360,60,20+lvl*45);});}
export function p_dot_matrix(ctx,W,H,rng){const bh=rng()*360,sz=6+rng()*6|0,sd=rng()*9999|0;ctx.fillStyle='#030308';ctx.fillRect(0,0,W,H);const R=H/sz|0,C=W/sz|0;for(let r=0;r<R;r++)for(let c=0;c<C;c++){const v=fbm(c/C,r/R,sd,3,2);ctx.fillStyle=`hsl(${(bh+c*5+r*4)%360},80%,${30+v*50}%)`;ctx.beginPath();ctx.arc(c*sz+sz/2,r*sz+sz/2,sz*.4*v,0,Math.PI*2);ctx.fill();}}
export function p_sort_base(ctx,W,H,rng){const bh=rng()*360,id=ctx.createImageData(W,H),d=id.data;for(let y=0;y<H;y++)for(let x=0;x<W;x++){const[r,g,b]=hsl2rgb((bh+x/W*180+y/H*180)%360,60+x/W*30,20+y/H*50);setpx(d,(y*W+x)*4,r,g,b);}ctx.putImageData(id,0,0);}

